Reorganize code to add static body for memory screen.
flutter/devtools pull request #5965
Opened 2023-06-27 22:37 UTC by polina-c

2023-07-03 20:15 UTC, polina-c commented on packages/devtools_app/lib/src/app.dart
> +      memoryAnalysisScreenId: (_, __, args, ____) {
Our standard navigation only works if there is live connection. We do not have mechanism to navigate to the same screen with connection and without it. If I pass `ScreenMetaData.memory.id` as route on button click at landing page, navigation does not happen.

So, with current mechanism we need different route to connect to the screen offline. 

I suggest to review/refactor this separately, in a right way, when we implement offline pattern.

2023-07-05 16:15 UTC, kenzieschmoll commented on packages/devtools_app/lib/src/app.dart
> +      memoryAnalysisScreenId: (_, __, args, ____) {
> Our standard navigation to a screen only works if there is live connection.

Not necessarily. We already can navigate to the app size screen and any standalone screens without an app connection. I'd take another look at the stack trace - my guess is that the live connection requirement is coming from the memory screen code itself.

2023-07-05 16:18 UTC, kenzieschmoll commented on packages/devtools_app/lib/src/app.dart
> +      memoryAnalysisScreenId: (_, __, args, ____) {
Fine to refactor later though. Please hide this route behind the `FeatureFlags.memoryAnalysis` flag. We don't want a user to be able to navigate to a screen that is not shipped.

2023-07-05 16:20 UTC, polina-c commented on packages/devtools_app/lib/src/app.dart
> +      memoryAnalysisScreenId: (_, __, args, ____) {
The code is copy-pasted from what we do for app size one block before:

```
appSizeScreenId: (_, __, args, ____) {
        final embed = isEmbedded(args);
        return DevToolsScaffold.withChild(
          key: const Key('appsize'),
          embed: embed,
          child: MultiProvider(
            providers: _providedControllers(),
            child: const AppSizeBody(),
          ),
        );
      },
```

2023-07-05 16:55 UTC, kenzieschmoll commented on packages/devtools_app/lib/src/app.dart
> +      memoryAnalysisScreenId: (_, __, args, ____) {
> The code is copy-pasted from what we do for app size one block before:

I'm not following. How does this relate to navigation? Navigation to the app size screen (which does not require an app connection) happens here: https://github.com/flutter/devtools/blob/master/packages/devtools_app/lib/src/framework/landing_screen.dart#L351

I am saying that if you were unable to navigate to the memory screen without having an app connection, then that likely is due to code from the memory screen that assumes we have a connected app - not code from the navigation framework, which has no understanding of app connected state.

2023-07-05 17:26 UTC, kenzieschmoll commented on packages/devtools_app/lib/src/app.dart
> +      memoryAnalysisScreenId: (_, __, args, ____) {
Discussed offline. Fine to leave as is for now - we will likely refactor how both the app size and memory screens are accessed for static mode here soon with the evolution of static tooling support in DevTools.

2023-07-05 17:27 UTC, kenzieschmoll commented on packages/devtools_app/lib/src/app.dart
> +      memoryAnalysisScreenId: (_, __, args, ____) {
```suggestion
  if (FeatureFlags.memoryAnalysis)
      memoryAnalysisScreenId: (_, __, args, ____) {
```

2023-07-05 17:27 UTC, kenzieschmoll requested changes
please hide behind the feature flag, then lgtm

2023-07-05 22:01 UTC, kenzieschmoll approved these changes

2023-07-06 17:33 UTC, merged